[package]
name = "brackens_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { workspace = true }

glam = { workspace = true }

log = "0.4.17"
env_logger = "0.10.0"
instant = "0.1.12"
